# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/speakers/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('profile', models.FileField(upload_to=b'')),
                ('status', models.IntegerField(choices=[(1, 'Applied'), (2, 'Reviewing'), (3, 'Accepted'), (4, 'Rejected'), (5, 'Previous'), (6, 'Current')])),
                ('previous_talk_link', models.URLField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
