# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerapplicationdata',
            name='status',
            field=models.IntegerField(choices=[(1, 'Applied'), (2, 'Reviewing'), (3, 'Accepted'), (4, 'Rejected'), (5, 'Previous'), (6, 'Current')], default=1),
        ),
    ]
