# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20200128_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerapplicationdata',
            name='profile',
            field=models.FileField(upload_to='profile/speakers/'),
        ),
    ]
