# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20200128_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerapplicationdata',
            name='previous_talk_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
