# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
