# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplicationdata',
            name='status',
            field=models.IntegerField(choices=[(1, b'Applied'), (2, b'Reviewing'), (3, b'Accepted'), (4, b'Rejected')], default=1),
        ),
    ]
