# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20200128_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplicationdata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/sponsors/'),
        ),
        migrations.AlterField(
            model_name='sponsordata',
            name='Image',
            field=models.ImageField(upload_to=b'images/sponsors/'),
        ),
    ]
