# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20200128_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsordata',
            name='Website',
        ),
        migrations.AddField(
            model_name='sponsorapplicationdata',
            name='Website',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorapplicationdata',
            name='status',
            field=models.IntegerField(choices=[(1, b'Applied'), (2, b'Reviewing'), (3, b'Accepted'), (4, b'Rejected'), (5, b'Previous'), (6, b'Current')], default=1),
        ),
    ]
